// Codec and registration for x/aegisvm

package types

import (
	"github.com/cosmos/cosmos-sdk/codec"
	cdctypes "github.com/cosmos/cosmos-sdk/codec/types"
	sdk "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice" // for future gRPC registration
)

// RegisterCodec registers the module's types on the legacy amino codec
func RegisterCodec(cdc *codec.LegacyAmino) {
	cdc.RegisterConcrete(&MsgDeployContract{}, "aegisvm/DeployContract", nil)
	cdc.RegisterConcrete(&MsgExecuteContract{}, "aegisvm/ExecuteContract", nil)
	cdc.RegisterConcrete(&MsgMigrateContract{}, "aegisvm/MigrateContract", nil)
	cdc.RegisterConcrete(&MsgUpdateAdmin{}, "aegisvm/UpdateAdmin", nil)
}

// RegisterInterfaces registers the module's interface types
func RegisterInterfaces(registry cdctypes.InterfaceRegistry) {
	registry.RegisterImplementations((*sdk.Msg)(nil),
		&MsgDeployContract{},
		&MsgExecuteContract{},
		&MsgMigrateContract{},
		&MsgUpdateAdmin{},
	)

	// Note: In production, use protoc-generated service descriptors
	// msgservice.RegisterMsgServiceDesc(registry, &_Msg_serviceDesc)
}

var (
	amino     = codec.NewLegacyAmino()
	ModuleCdc = codec.NewProtoCodec(cdctypes.NewInterfaceRegistry())
)

func init() {
	RegisterCodec(amino)
	amino.Seal()
}

// Service descriptors for gRPC would be generated by protoc in production

// RegisterMsgServer registers the message server
func RegisterMsgServer(s interface{}, srv MsgServer) {
	// gRPC server registration
	// In production, this would be generated by protoc
}

// RegisterQueryServer registers the query server
func RegisterQueryServer(s interface{}, srv QueryServer) {
	// gRPC server registration
	// In production, this would be generated by protoc
}
